### ISSUE TITLE
Code guide for CSS

### ISSUE THREAD

**Issue by moriko** [moriko/moriko.github.io#1]
### <a name='TOC'>Table of Contents</a>

1. [Syntax](#syntax)
1. [Declaration order](#order)
1. [Prefixed properties](#prefix)
1. [Single declarations](#declarations)
1. [Shorthand notation](#shorthand)
1. [Operators in Sass](#operators)
1. [Comments](#comments)
1. [Class names](#classnames)
1. [Selectors](#selectors)

## <a name='syntax'>Syntax</a>

- Use soft tabs with four spaces—they're the only way to guarantee code renders the same in any environment.
- When grouping selectors, keep individual selectors to a single line.
- Include one space before the opening brace of declaration blocks for legibility.
- Place closing braces of declaration blocks on a new line.
- Include one space after `:` for each declaration.
- Each declaration should appear on its own line for more accurate error reporting.
- End all declarations with a semi-colon. The last declaration's is optional, but your code is more error prone without it.
- Comma-separated property values should include a space after each comma (e.g., `box-shadow`).
- Include spaces after commas within `rgb()`, `rgba()`, `hsl()`, `hsla()`, or `rect()` values..
- Lowercase all hex values, e.g., `#fff`. Lowercase letters are much easier to discern when scanning a document as they tend to have more unique shapes.
- Use shorthand hex values where available, e.g., `#fff` instead of `#ffffff`.
- Quote attribute values in selectors, e.g., `input[type="text"]`. They’re only optional in some cases, and it’s a good practice for consistency.
- Avoid specifying units for zero values, e.g., margin: 0; instead of margin: 0px;.

```css
/* Bad CSS */
.selector, .selector-secondary, .selector[type=text] {
    padding:15px;
    margin:0px 0px 15px;
    background-color:rgba(0,0,0,0.5);
    box-shadow:0px 1px 2px #CCC,inset 0 1px 0 #FFFFFF
}

/* Good CSS */
.selector,
.selector-secondary,
.selector[type="text"] {
    padding: 15px;
    margin-bottom: 15px;
    background-color: rgba(0, 0, 0, 0.5);
    box-shadow: 0 1px 2px #ccc, inset 0 1px 0 #fff;
}
```

## <a name='order'>Declaration order</a>

For a complete list of properties and their order, please see [Recess](http://twitter.github.io/recess/).

## <a name='prefix'>Prefixed properties</a>

When using vendor prefixed properties, indent each property such that the declaration's value lines up vertically for easy multi-line editing.

```css
.selector {
  -webkit-box-shadow: 0 1px 2px rgba(0, 0, 0,.15);
          box-shadow: 0 1px 2px rgba(0, 0, 0,.15);
}
```

## <a name='declarations'>Single declarations</a>

In instances where a rule set includes only one declaration, consider removing line breaks for readability and faster editing. Any rule set with multiple declarations should be split to separate lines.

The key factor here is error detection—e.g., a CSS validator stating you have a syntax error on Line 183. With a single declaration, there's no missing it. With multiple declarations, separate lines is a must for your sanity.

```css
/* Single declarations on one line */
.span1 { width: 60px; }
.span2 { width: 140px; }
.span3 { width: 220px; }

/* Multiple declarations, one per line */
.sprite {
    display: inline-block;
    width: 16px;
    height: 15px;
    background-image: url(../img/sprite.png);
}
.icon           { background-position: 0 0; }
.icon-home      { background-position: 0 -20px; }
.icon-account   { background-position: 0 -40px; }
```

## <a name='shorthand'>Shorthand notation</a>

Strive to limit use of shorthand declarations to instances where you must explicitly set all the available values. Common overused shorthand properties include:

- `padding`
- `margin`
- `font`
- `background`
- `border`
- `border-radius`

Often times we don't need to set all the values a shorthand property represents. For example, HTML headings only set top and bottom margin, so when necessary, only override those two values. Excessive use of shorthand properties often leads to sloppier code with unnecessary overrides and unintended side effects.

```css
/* Bad example */
.element {
    margin: 0 0 10px;
    background: red;
    background: url("image.jpg");
    border-radius: 3px 3px 0 0;
}

/* Good example */
.element {
    margin-bottom: 10px;
    background-color: red;
    background-image: url("image.jpg");
    border-top-left-radius: 3px;
    border-top-right-radius: 3px;
}
```

## <a name='operators'>Operators in Sass</a>

For improved readability, wrap all math operations in parentheses with a single space between values, variables, and operators.

```css
// Bad example
.element {
    margin: 10px 0 $variable*2 10px;
}

// Good example
.element {
    margin: 10px 0 ($variable * 2) 10px;
}
``` 

## <a name='comments'>Comments</a>

Code is written and maintained by people. Ensure your code is descriptive, well commented, and approachable by others. Great code comments convey context or purpose. Do not simply reiterate a component or class name.

Be sure to write in complete sentences for larger comments and succinct phrases for general notes.

```css
/* Bad example */
/* Modal header */
.modal-header {
  ...
}

/* Good example */
/* Wrapping element for .modal-title and .modal-close */
.modal-header {
  ...
}
```

## <a name='classnames'>Class names</a>

- Keep classes lowercase and use dashes (not underscores or camelCase). Dashes serve as natural breaks in related class (e.g., `.btn` and `.btn-danger`).
- Avoid excessive and arbitrary shorthand notation. `.btn` is useful for button, but `.s` doesn't mean anything.
- Keep classes as short and succinct as possible.
- Use meaningful names; use structural or purposeful names over presentational.
- Prefix classes based on the closest parent or base class.
- Use `.js-*` classes to denote behavior (as opposed to style), but keep these classes out of your CSS.

It's also useful to apply many of these same rules when creating Sass variable names.

## <a name='selectors'>Selectors</a>

- Use classes over generic element tag for optimum rendering performance.
- Avoid using several attribute selectors (e.g., [class^="..."]) on commonly occuring components. Browser performance is known to be impacted by these.
- Keep selectors short and strive to limit the number of elements in each selector to three.
- Scope classes to the closest parent only when necessary (e.g., when not using prefixed classes).

```css
/* Bad example */
span { ... }
.page-container #stream .stream-item .tweet .tweet-header .username { ... }
.avatar { ... }

/* Good example */
.avatar { ... }
.tweet-header .username { ... }
.tweet .avatar { ... }
```

**Comment by moriko** [comment]
# V2

### <a name='TOC'>Table of Contents</a>

1. [Syntax](#syntax)
1. [Declaration order](#order)
1. [Prefixed properties](#prefix)
1. [Single declarations](#declarations)
1. [Shorthand notation](#shorthand)
1. [Operators in Sass](#operators)
1. [Comments](#comments)
1. [Class names](#classnames)
1. [Selectors](#selectors)

## <a name='syntax'>Syntax</a>

- Use soft tabs with four spaces - they're the only way to guarantee code renders the same in any environment.
- When grouping selectors, keep individual selectors to a single line.
- Include one space before the opening brace of declaration blocks for legibility.
- Place closing braces of declaration blocks on a new line.
- Include one space after and no space before `:` for each declaration.
- Each declaration should appear on its own line for more accurate error reporting.
- End all declarations with a semi-colon. The last declaration's is optional, but your code is more error prone without it.
- Comma-separated property values should include a space after each comma (e.g., `box-shadow`).
- Include spaces after commas within `rgb()`, `rgba()`, `hsl()`, `hsla()`, or `rect()` values.
- Lowercase all hex values, e.g., `#fff`. Lowercase letters are much easier to discern when scanning a document as they tend to have more unique shapes.
- Use shorthand hex values where available, e.g., `#fff` instead of `#ffffff`.
- Quote attribute values in selectors, e.g., `input[type="text"]`. They’re only optional in some cases, and it’s a good practice for consistency.
- Avoid specifying units for zero values, e.g., margin: 0; instead of margin: 0px;.

**Suggestion for better code readability:**
- Put a space before the opening brace `{` in rule declarations
- Put closing braces `}` of rule declarations on a new line
- Put blank lines between rule declarations

```css
/* Bad CSS */
.selector, .selector-secondary, .selector[type=text] {
    padding:15px;
    margin:0px 0px 15px;
    background-color:rgba(0,0,0,0.5);
    box-shadow:0px 1px 2px #CCC,inset 0 1px 0 #FFFFFF
}

/* Good CSS */
.selector,
.selector-secondary,
.selector[type="text"] {
    padding: 15px;
    margin-bottom: 15px;
    background-color: rgba(0, 0, 0, 0.5);
    box-shadow: 0 1px 2px #ccc, inset 0 1px 0 #fff;
}
```

## <a name='order'>Declaration orders</a>

Related property declarations should be grouped together following the order:

- `@extend`, `@include` and etc.;
- Styling;
- `@include media-query`.

```css
.element {
    @include clearfix();
    float: left;
    width: 200px;
    height: 200px;

    &:last-child {
        margin-right: 0;
    }

    @include media-query($mobile) {
        width: 150px;
    }
}
```

## <a name='prefix'>Prefixed properties</a>

When using vendor prefixed properties, indent each property such that the declaration's value lines up vertically for easy multi-line editing.

```css
.selector {
  -webkit-box-shadow: 0 1px 2px rgba(0, 0, 0, 0.15);
          box-shadow: 0 1px 2px rgba(0, 0, 0, 0.15);
}
```

## <a name='declarations'>Single declarations</a>

In instances where a rule set includes only one declaration, consider removing line breaks for readability and faster editing. Any rule set with multiple declarations should be split to separate lines.

The key factor here is error detection - e.g., a CSS validator stating you have a syntax error on Line 183. With a single declaration, there's no missing it. With multiple declarations, separate lines is a must for your sanity.

```css
/* Single declarations on one line */
.span1 { width: 60px; }
.span2 { width: 140px; }
.span3 { width: 220px; }

/* Multiple declarations, one per line */
.sprite {
    display: inline-block;
    width: 16px;
    height: 15px;
    background-image: url(../img/sprite.png);
}
.icon         { background-position: 0 0; }
.icon-home    { background-position: 0 -20px; }
.icon-account { background-position: 0 -40px; }
```

## <a name='shorthand'>Shorthand notation</a>

Strive to limit use of shorthand declarations to instances where you must explicitly set all the available values. Common overused shorthand properties include:

- `padding`
- `margin`
- `font`
- `background`
- `border`
- `border-radius`

Often times we don't need to set all the values a shorthand property represents. For example, HTML headings only set top and bottom margin, so when necessary, only override those two values. Excessive use of shorthand properties often leads to sloppier code with unnecessary overrides and unintended side effects.

```css
/* Bad example */
.element {
    margin: 0 0 10px;
    background: red;
    background: url("image.jpg");
    border-radius: 3px 3px 0 0;
}

/* Good example */
.element {
    margin-bottom: 10px;
    background-color: red;
    background-image: url("image.jpg");
    border-top-left-radius: 3px;
    border-top-right-radius: 3px;
}
```

## <a name='operators'>Operators in Sass</a>

For improved readability, wrap all math operations in parentheses with a single space between values, variables, and operators. It is also good to use interpolation syntax for variables in selectors and property names. In most cases this isn’t any better than using a variable, but using `#{}` does mean that any operations near it will be treated as [plain CSS](http://sassmeister.com/gist/3bcc5d172f4784145e5f):

```css
// Bad example
.element {
    padding: 10px 0 $variable*2 10px;
    margin: 0 -$variable;
}

// Good example
.element {
    padding: 10px 0 ($variable * 2) 10px;
    margin: 0 -#{$variable};
}
``` 

## <a name='comments'>Comments</a>

Code is written and maintained by people. Ensure your code is descriptive, well commented, and approachable by others. Great code comments convey context or purpose. Do not simply reiterate a component or class name.

Be sure to write in complete sentences for larger comments and succinct phrases for general notes.

```css
/* Bad example */
/* Modal header */
.modal-header {
  ...
}

/* Good example */
/* Wrapping element for .modal-title and .modal-close */
.modal-header {
  ...
}
```

## <a name='classnames'>Class names</a>

- Keep classes lowercase and use dashes (not underscores or camelCase). Underscores are OK if you're using [BEM](http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/). Dashes serve as natural breaks in related class (e.g., `.btn` and `.btn-danger`).
- Avoid excessive and arbitrary shorthand notation. `.btn` is useful for button, but `.s` doesn't mean anything.
- Keep classes as short and succinct as possible.
- Use meaningful names; use structural or purposeful names over presentational.
- Prefix classes based on the closest parent or base class.
- Use `.js-*` classes to denote behaviour (as opposed to style), but keep these classes out of your CSS.
- Do not use ID selectors. While it is possible to select elements by ID in CSS, it should generally be considered an anti-pattern. ID selectors introduce an unnecessarily high level of specificity to your rule declarations, and they are not reusable.

It's also useful to apply many of these same rules when creating Sass variable names.

## <a name='selectors'>Selectors</a>

- Use classes over generic element tag for optimum rendering performance.
- Avoid using several attribute selectors (e.g., `[class^="..."]`) on commonly occurring components. Browser performance is known to be impacted by these.
- Keep selectors short and strive to limit the number of elements in each selector to three.
- Scope classes to the closest parent only when necessary (e.g., when not using prefixed classes).

```css
/* Bad example */
span { ... }
.page-container #stream .stream-item .tweet .tweet-header .username { ... }
.avatar { ... }

/* Good example */
.avatar { ... }
.tweet-header .username { ... }
.tweet .avatar { ... }
```
